# Generated by Django 3.0.5 on 2020-05-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_slug',
            field=models.SlugField(null=True),
        ),
    ]
